apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-proxy-operator
  namespace: minecraft-system
  labels:
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: mc-proxy-operator
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: manager
          image: luisito666/mc-proxy-operator:v1.0.0
          ports:
            - containerPort: 25565
              name: mc-java
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
            - containerPort: 8081
              name: health
              protocol: TCP
          env:
            - name: JAVA_LISTEN_ADDR
              value: ":25565"
            - name: METRICS_ADDR
              value: ":8080"
            - name: HEALTH_PROBE_ADDR
              value: ":8081"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
