apiVersion: v1
kind: Namespace
metadata:
  name: minecraft-system
  labels:
    app.kubernetes.io/name: mc-proxy-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: mc-servers
  labels:
    app.kubernetes.io/name: mc-proxy-operator
    app.kubernetes.io/component: game-servers
